### ISSUE TITLE
Exist for NFT bridge-Apps for the Blockchains ?

### ISSUE THREAD

**Issue by Kamaloka-music** [protocol/nft-website#115]
<!--
Hi, im new to the NFT Universe :)
i have many Questions. Dont know, im right here..

I want to Know , is there for NFTs
any Bridge- Apps or Programs to
Convert the many different NFT Blockchains?

WAX , Enjin, Binance, and so on...

**Comment by jessicaschilling** [comment]
Can you explain more what you mean?

**Comment by jessicaschilling** [comment]
Closing this for now, but please feel free to re-open if you want to add more details.
