### ISSUE TITLE
Post-MVP user testing

### ISSUE THREAD

**Issue by jessicaschilling** [protocol/nft-website#12]
This issue is for outlining a plan for post-MVP user testing. It may need to be broken up into multiple issues as plans solidify.

Primary focus for this round of user testing will be two-fold:
- Is content (and content hierarchy) correct?
- Is basic branding (name, color scheme) correct?

@atopal - you're more aware of the hackathon opportunities for user testing. Are you able to outline?

**Comment by atopal** [comment]
Notes: 
* web3weekend hackathon starts on May 28 and ends on May 29
* We'll talk about nft school on May 27
* We intend to double the number of paticipants on May 28
* Prepare user testing for week of May 31st.
* Invite participants on May 28
* 4 participants
* Focus on expectations/gaps
* Fold insights back into launch panning

**Comment by jessicaschilling** [comment]
@atopal Makes sense. Would suggest the following basic flow for an interview guide — intentionally keeping things pretty vague in order to let each conversation go in its most useful direction. With an interview set of four participants, we're better off digging deep into what each participant cares about rather than try to get a cross-section for comparison. 

1. Tell us about yourself: name, location, day job description, anything else that would be helpful for us to know about you.
2. Why did you sign up for Web3 Weekend? What did you hope to get out of it? What did you actually get out of it?
3. What was your level of knowledge about NFTs before starting the hackathon? How would you describe your NFT knowledge now?
4. Did you use any NFT School content to help you during the hackathon? If not, why not? If so, which items? How were/weren't they helpful?
5. (This one will need to be modified or even eliminated on the fly based on answers to previous questions) We'd be grateful for you to think out loud while walking through one of the pieces of NFT School content (suggest either [NFT Basics](https://nft-school-staging.on.fleek.co/concepts/non-fungible-tokens/) or [First Steps](https://nft-school-staging.on.fleek.co/tutorial/first-steps/) depending on their level of expertise). If you've already read this content, you can relay your thoughts the first time you read it; otherwise, just quickly read/scan and think out loud. Don't be afraid to be mean if there's something you think is confusing or poorly done.
5. We know there's a lot of content still under construction on this site. Do you have items here that you'd want to prioritize to help boost your learning? Is there anything missing from the navigation that should be there?
6. How could we make NFT School more useful for people like you?
7. Anything else we forgot to discuss, or that you'd want to change/add/subtract about NFT School?

**IMPORTANT QUESTION:** "we'll talk about nft school on May 27" sounds like we need to have the site live by then, even if only with the content as it exists at the time. Please confirm/deny?

**Comment by atopal** [comment]
Thanks Jessica. We are going to talk about NFT school on Friday.

**Comment by jessicaschilling** [comment]
User testing summary discussion taking place Fri 25 June. While for test subject privacy reasons it's not feasible to share full details in this issue, we'll be capturing all work suggested in prioritized issues in this repo. Closing this issue — thanks to all who participated in this process!
