### ISSUE TITLE
[SUGGESTION] (your title goes here)

### ISSUE THREAD

**Issue by jtchien0925** [protocol/nft-website#125]
Hello, 

First of all, great project. 

I wonder if you will be interested in exploring an integration option with Galaxy protocol? 

https://docs.galaxy.eco/1-hello-galaxy

**Comment by atopal** [comment]
Thanks for the feedback. What kind of integration did you have in mind?

**Comment by dchoi27** [comment]
Closing for now! Feel free to reach back out
