### ISSUE TITLE
[CONTENT REQUEST] (Code Example for BULK upload an entire NFT collection on OpenSea with LAZY MINTING)

### ISSUE THREAD

**Issue by dvdkite** [protocol/nft-website#130]
Hello. I came across you lazy minting tutorial and it is very well done. I still have to try everything as I'm still in to the artistic creation process to generate a 10k nft collections. It would be really awesome (and it would complete your lazy minting tutorial )to understand how can I actually made a bulk upload of a 10k collection on Open Sea on the ETHEREUM blockchain with the Lazy Minting.

Thanks

**Comment by dchoi27** [comment]
Hey there! So the lazy minting tutorial is more geared towards writing your own contracts and minting them yourselves. If you're looking to mint a bunch of NFTs on OpenSea specifically, you should check out their docs to see if there is a tutorial or considerations for doing so (could see rate limits being an issue for instance, but this would be specific to OpenSea). Let us know if you have any more questions!
