### ISSUE TITLE
[CONTENT] Tutorials - Building a minting and marketplace app - Flow

### ISSUE THREAD

**Issue by dchoi27** [protocol/nft-website#146]
Alongside #145, it would be cool to have a tutorial for @jochasinga 's pet shop tutorial on Flow ([Flowwow](https://github.com/jochasinga/flowwow)). This is a placeholder issue for that tutorial, covering the minting service part and the marketplace part of Flowwow for devs new to NFTs and Flow.

**Comment by jochasinga** [comment]
This should be closed @dchoi27
