### ISSUE TITLE
[CONTENT] Tutorials - Minting thousands of NFTs at once

### ISSUE THREAD

**Issue by dchoi27** [protocol/nft-website#148]
Per [community requests](https://github.com/ipfs-shipyard/nft.storage/issues/426), we should make a page `tutorials/minting-many-nfts` that show how to mint many NFTs at once using the same code using NFT.Storage and an EVM-compatible smart contract.

This is slightly lower priority because it is likely to be more useful for new developers, though this tutorial could be useful showing some of the considerations of minting a lot of NFTs at once (tracking success, chain speed, etc.). Can also point folks to just using an existing minting service to actually do their minting (so this tutorial would be more to show what goes on underneath the hood).

**Comment by jochasinga** [comment]
We already have [Batch-minting NFTs on Ethereum](https://nftschool.dev/guides/batch-minting/) hopefully it suffices for now.
