### ISSUE TITLE
[SOFT LAUNCH] Add inbound links from other PL properties

### ISSUE THREAD

**Issue by jessicaschilling** [protocol/nft-website#16]
Setting this issue up as separate from #10, but may be able to roll them in together.

Find opportunities on other PL web properties for linking to this site (IPFS docs, Filecoin docs, Dweb Primer, IPFS blog, etc), and implement links.

**Comment by jessicaschilling** [comment]
Update: Prioritizing this work in order to encourage quiet traffic to the site in July and due to formal launch likely being delayed somewhat.

**Comment by jessicaschilling** [comment]
Cross-linking opportunities (note some may be struck out upon closer examination):

- [ ] https://docs.ipfs.io/how-to/best-practices-for-nft-data/
- [ ] https://docs.ipfs.io/how-to/mint-nfts-with-ipfs/
- [ ] https://docs.filecoin.io/reference/
- [ ] https://blog.ipfs.io/2021-06-17-opensea-ipfs-filecoin/
- [ ] https://blog.ipfs.io/2021-06-11-interplanetary-timelessness/
- [ ] https://blog.ipfs.io/2021-06-03-ipfs-filecoin-content-persistence/
- [ ] https://blog.ipfs.io/2021-05-14-minting-fresh-nfts-with-ipfs/
- [ ] https://blog.ipfs.io/2021-05-13-recapping-nft-hack/
- [ ] https://blog.ipfs.io/2021-04-05-storing-nfts-on-ipfs/
- [ ] https://filecoin.io/blog/posts/opensea-decentralizes-and-persists-nft-storage-with-ipfs-and-filecoin/
- [ ] https://filecoin.io/blog/posts/ipfs-filecoin-and-content-persistence/
- [ ] https://filecoin.io/blog/posts/introducing-nft.storage-free-decentralized-storage-for-nfts/
- [ ] https://filecoin.io/blog/posts/truffle-suite-launches-nft-development-template-with-filecoin-box/

**Comment by jessicaschilling** [comment]
@atopal I think we'd be OK to link to the front of nftschool.dev as a "suggested resource" or similar on each of the pages listed in the previous comment. Can you confirm this is an OK approach? If yes I'll get started PRing or making content requests.

**Comment by atopal** [comment]
Yes, please go ahead, Jessica.

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/nft.storage/pull/209/ will take care of nft.storage FAQ addition.

**Comment by jessicaschilling** [comment]
https://github.com/ipfs/ipfs-docs/pull/819 will take care of IPFS docs.

**Comment by jessicaschilling** [comment]
@emilymvaughan - as discussed, can you please make the following three small changes Filecoin blog posts? Thank you!

- [ ] https://filecoin.io/blog/posts/introducing-nft.storage-free-decentralized-storage-for-nfts/ - please insert a first bullet point that says "NFT School" and is linked to https://nftschool.dev
![image](https://user-images.githubusercontent.com/1507828/123162149-7ebf1180-d42d-11eb-88cc-4a7fe370bee3.png)

- [ ] https://filecoin.io/blog/posts/ipfs-filecoin-and-content-persistence/ - Please do the same but make "NFT School" the second item in the list after "nft.storage:
![image](https://user-images.githubusercontent.com/1507828/123162420-d2315f80-d42d-11eb-9898-8f4e32d9f264.png)

- [ ] https://filecoin.io/blog/posts/opensea-decentralizes-and-persists-nft-storage-with-ipfs-and-filecoin/ - Same, but please make "NFT School" the second bullet point:
![image](https://user-images.githubusercontent.com/1507828/123162623-102e8380-d42e-11eb-98c0-8d7aa8c70d81.png)

**Comment by jessicaschilling** [comment]
All items from task list are complete; closing this issue.
