### ISSUE TITLE
Update Algolia, other settings in config.js

### ISSUE THREAD

**Issue by jessicaschilling** [protocol/nft-website#22]
Update settings in Vuepress' `config.js` file for consistency and depersonalization from IPFS docs:

- [ ] Algolia search config
- [x] Social card: author name and related Twitter (@protocollabs?)
- [x] Speedcurve settings

Others TBD.

**Comment by jessicaschilling** [comment]
@zebateira Do you think it's worth trying to submit again from scratch, instead of waiting to see if they reply to your email?

**Comment by zebateira** [comment]
@jessicaschilling we can try, but the form only allows to submit an email and the site url. So if it's not live yet there's no way for them know the github repo url.
I suggest waiting for their response, and if we don't hear back soon we can do soft-launch so they can access the url, and only after they respond and we set it up we can announce go live.

**Comment by jessicaschilling** [comment]
@zebateira Can you please remove Algolia search for now, and we'll just use the built-in (not great Vuepress search plugin) until soft launch? Doing so can close this issue. I've also added https://github.com/protocol/nft-website/issues/61 for submitting our application to Algolia post-soft-launch. 🙏
