### ISSUE TITLE
[SUGGESTION] (added content)

### ISSUE THREAD

**Issue by MissyM0** [protocol/nft-website#231]
Hi there, I just thought it would be helpful to touch base on the differences between buying artwork and buying an NFT for a game. I've read that just because  you buy and NFT doesn't necessarily mean you own it. 
Please correct me if I'm wrong. 
I've been researching nfts and crypto for 7 months now and still have so many inanwered questions.

**Comment by jochasinga** [comment]
@MissyM0 we are adding an [encyclopedia section](https://github.com/protocol/nft-website/pull/274) that will hopefully answer some of your questions. Let me know if you have more questions or a content idea and I'll reopen this.
