### ISSUE TITLE
Why not use CryptoKitties as example instead of CryptoPunks?

### ISSUE THREAD

**Issue by androidhead** [protocol/nft-website#233]
In the section NFT Basics, I noticed that it reads "Among the earliest NFT experiments is CryptoPunks".  I believe CryptoKitties was possibly _the_ first NFT project, and sent precedents used by other NFT projects (including CryptoPunks).  This being the case, why not mention CryptoKitties here instead of (or in addition to) CryptoPunks?

**Comment by jochasinga** [comment]
My assumption is the 8-bit look and feel of NFT.school might be partially inspired by CryptoPunks (correct me if I'm wrong, anyone). However, I agree that CryptoKitties *is* indeed the trailblazer. I don't see any harm in including this reference/homage.

**Comment by jochasinga** [comment]
@androidhead I'm closing this for now. Feel free to move this to a discussion or re-open later.
