### ISSUE TITLE
[CONTENT] Content persistence

### ISSUE THREAD

**Issue by yusefnapora** [protocol/nft-website#24]
This issue is for drafting content for the following:
- Title: Content persistence
- Address: `/concepts/content-persistence/`

**This content is slated for MVP, but might not be included in 20 May round.**

This is a potentially tricky one. 

We want to call out that IPFS doesn't give you "persistence" for free; you need to either run your IPFS nodes 24/7 or outsource to a pinning service. We also want to talk about decentralized storage (e.g. Filecoin) and point to nft.storage as an example that is both decentralized and free to use. 

This is working against the common misconception that when you add your data to IPFS, it essentially becomes the network's problem from then on. Since educating people about this is revealing a limitation of IPFS that they might not have been aware of, we should try to steer people to the best and simplest solution for their new problem. For most, that's probably nft.storage, since it's free and makes persistence "someone else's problem", where the "someone else" is Protocol Labs. 

That said, we also need to present alternatives for people that either don't trust our generosity or just want to have more control over their data.

Some questions:

- Why _wouldn't_ you use nft.storage?
  - Hedging your bets on PL's generosity running out?
- Can we point to alternative solutions for people that want to use Filecoin apart from nft.storage? 
  - E.g. Textile Buckets?
- Do we want to link to pinning services? 
  - Which ones?
- Should we link to IPFS cluster docs?

**Comment by jessicaschilling** [comment]
@yusefnapora - per our sync discussion, assigning this one to you just in case there's time to squeeze even some basic content in here for 28 May 🙏
