### ISSUE TITLE
[PAGE ISSUE] Mint with NFT.storage and Polygon HardhatError: HH110: Invalid JSON-RPC response received: error code: 1020

### ISSUE THREAD

**Issue by jokofler** [protocol/nft-website#243]
Hello guys, thank you for your guide on how to mint nfts on polygon. Till deploying the smart cotnract everything works fine but when I do npx hardhat run scripts/deploy-contract.mjs --network PolygonMumbai

the following error occurs:
HardhatError: HH110: Invalid JSON-RPC response received: error code: 1020

Do you know what to do? That would be amazing!

**Comment by jochasinga** [comment]
@itsPiyushMaheshwari would you mind looking into this?

**Comment by itsPiyushMaheshwari** [comment]
Please try with dedicated rpc like Alchemy, infura etc.
