### ISSUE TITLE
Mint 3d model

### ISSUE THREAD

**Issue by usama1050** [protocol/nft-website#246]
Hello! 
I checked  your nft-school-examples/end-to-end code its working perfectly with the image files(png,jpg etc ) but not working when i mint 3d  model I want to mint the 3d model (file format .glb).
it gives me error on nft.storage

Error: property image must be a Blob or File object at this point

const metadata = await client.store({
    name,
    description,
    image, //
  });

**Comment by jochasinga** [comment]
It should work with `.glb` file or any kind of binary file. You just have to convert it to `Blob` or `File` object before passing to `store()`.

```js
const  model = await fetch('/path/to/character.glb')
const imgdata = await model.blob()  // Convert to a Blob object
const image = new File([imgdata], 'character.glb', {type: 'model/gltf-binary'})
const nft = {
      image, // use image Blob as `image` field
      name: 'character.glb',
      description: 'Data of NFT #1',
      properties: { ...otherProps }
}
const metadata = await client.store(nft)
```
