### ISSUE TITLE
[CONTENT] Example apps and code samples

### ISSUE THREAD

**Issue by jessicaschilling** [protocol/nft-website#34]
This issue is for drafting content for the following:
- Title: Example apps and code samples
- Address: `/reference/example-apps-code-samples/`

**Contributions are welcome!** If you'd like to make the global NFT developer community better for everyone by creating a guide for this page, please leave a comment and someone from the core team will be in touch ASAP. 🙏

**Comment by jessicaschilling** [comment]
@johndmulhausen @yusefnapora @atopal Might this be something we could crowdsource for at least a barebones implementation: "what are your favorite example apps/code samples"? That's assuming there's enough out there already ...

Another option might be to link out to some of the repos we've seen submitted to the ecosystem/Awesome IPFS survey, though most of those are hackathon PoCs.

**Comment by atopal** [comment]
Yeah, real world examples would actually be preferable.

**Comment by jessicaschilling** [comment]
@yusefnapora @johndmulhausen If this is something you feel we could at least get out barebones prior to pausing work, LMK and I can share the ecosystem/Awesome projects database for you to mine for NFT examples 😊

**Comment by ch0mat0se** [comment]
@jessicaschilling - do you have any real world examples to share yet?

**Comment by jessicaschilling** [comment]
@ch0mat0se — work on this issue has been paused for now, but please feel free to follow this issue for future updates. Thank you!

**Comment by mager** [comment]
I think the tutorial everyone wants is, "Building a website that lets users mint your NFT". Something that covers the Solidity/ETH dev side, the node JS layer, as well as the frontend setup using React. Would love to see something like this on NFT School.

Great site by the way, I have learned a ton reading it.

**Comment by dchoi27** [comment]
Plan is to move the content that would be in this page to the Tutorials section. Closing for now!
