### ISSUE TITLE
[CONTENT] nft.storage end-to-end reference

### ISSUE THREAD

**Issue by johndmulhausen** [protocol/nft-website#39]
This issue is for drafting content for the following:
- Title: End-to-end experience
- Address: `/tutorial/end-to-end-experience/`

- How do you mint
- End-to-end storage story
- Reference

**Comment by jessicaschilling** [comment]
@johndmulhausen Saw some commits to `staging` ref this — let me know when you consider this issue ready for copy editing and/or closure.
