### ISSUE TITLE
[CONTENT] NFT marketplaces

### ISSUE THREAD

**Issue by jessicaschilling** [protocol/nft-website#45]
This issue is for drafting content for the following:
- Title: NFT marketplaces
- Address: `/reference/nft-marketplaces/`

**Note that content in a rough form exists on this page, but the intent is to make it more of a verified guide to marketplaces using best practices.**

**Comment by jessicaschilling** [comment]
@yusefnapora - per our discussion, assigning you this for the sake of at least getting an introductory paragraph and a basic list of links in there for 28 May. Thank you!

**Comment by yangwao** [comment]
Hey, I would like to nominate @KodaDot as we are doing quite a lot NFTs, used implemented Textile and plan to have Filecoin. Now having Subquery as indexer and willing to help educate NFT devs as we plan to run experimental NFT landscape, metaprime.network :)

**Comment by jessicaschilling** [comment]
@yangwao Thanks for chiming in - added in https://github.com/protocol/nft-website/pull/94.

**Comment by johndmulhausen** [comment]
Calling this done; certainly we have enough for launch here and the community can comment more on good marketplaces out there, which we should add over time, as we did when @yangwao chimed in.

**Comment by jessicaschilling** [comment]
@johndmulhausen  That's fine, but there's still cleanup work to do: right now the page encourages people to visit _this_ issue for the latest developments and to comment on more resources, which means that user will find a closed issue and think the work is done. We need to improve the CTA to make it more explicitly clear that readers are encouraged to add their sites.
![image](https://user-images.githubusercontent.com/1507828/123297818-280d1280-d4d5-11eb-8084-5fd8023bb884.png)

**Comment by jessicaschilling** [comment]
https://github.com/protocol/nft-website/pull/106 improves CTA language to close this issue.
