### ISSUE TITLE
Add Algolia search once approved for open-source use

### ISSUE THREAD

**Issue by jessicaschilling** [protocol/nft-website#61]
Splitting this out in its own issue from https://github.com/protocol/nft-website/issues/22 for post-MVP work.

Looks unlikely that Algolia will approve this site for an open-source license until MVP is launched and the URL has more public content. @zebateira — can you please re-submit to Algolia once the site is soft-launched with DNS correctly pointed? Thank you!

**Comment by zebateira** [comment]
@jessicaschilling sent the request using your email 🚀
