### ISSUE TITLE
CID breaks layout

### ISSUE THREAD

**Issue by atopal** [protocol/nft-website#82]
On mobile the CID on [this page](https://nftschool.dev/tutorial/end-to-end-experience/#how-ipfs-helps) leads to horizontal scrolling. Maybe we should add a word break?

**Comment by alanshaw** [comment]
For context:

![Image from iOS](https://user-images.githubusercontent.com/152863/119991828-c8991100-bfc1-11eb-928e-7e51b5d0f9b9.png)
