### ISSUE TITLE
[SUGGESTION] Add message about contributors to articles

### ISSUE THREAD

**Issue by atopal** [protocol/nft-website#90]
Since we want to attract contributors to the site, we should mention that others have contributed to articles. We currently advertise prominently that people can contribute, we should also highlight that others have done so already. Something like 

"Last modified: May 26, 2021, by NFTschool contributors" and link contributors to the Github page.

The last modified part is also important, but a separate feature.

**Comment by jessicaschilling** [comment]
"Last modified" work is being tracked in https://github.com/protocol/nft-website/issues/91.

@atopal are you wanting something dynamic (i.e. the GH profile URL for the last contributor) or just "by contributors" and a link to the MD source page?

**Comment by jessicaschilling** [comment]
@zebateira Per sync discussion earlier today, when you are able to troubleshoot https://github.com/protocol/nft-website/issues/91, can you please amend the footer text to read the following?

Last Updated: [date], [time] by [NFT School contributors like you]

... where `NFT School contributors like you` links to the GitHub edit page for the content in question (e.g. https://github.com/protocol/nft-website/edit/main/docs/reference/nft-marketplaces.md)?

**Comment by zebateira** [comment]
That link will request users to login first
<img width="815" alt="image" src="https://user-images.githubusercontent.com/2353186/121936573-ae8d5b80-cd41-11eb-9c42-db98b3040e1c.png">

Should we link directly to the markdown and leave the users to click the edit button?
Just double checking.

**Comment by jessicaschilling** [comment]
Crud, that's actually a very good point because we are already linking to the direct-edit URL in the feedback boxes:
![image](https://user-images.githubusercontent.com/1507828/121937322-ccd66580-cd07-11eb-8b5f-be4f841b3916.png)

You're right that it makes more sense to link directly to the markdown. However, can you please change that in the feedback box component as well?

**Comment by zebateira** [comment]
@jessicaschilling done! #95

**Comment by jessicaschilling** [comment]
@zebateira 🥳  Thanks so much!

**Comment by atopal** [comment]
Just confirming that we are linking to this view? https://github.com/protocol/nft-website/blob/main/docs/reference/nft-marketplaces.md

**Comment by jessicaschilling** [comment]
@atopal If you go to https://nftschool.dev/reference/nft-marketplaces/ (to match your example): Yes, both the "Edit this page" and "NFT School contributors" go to that page.

![image](https://user-images.githubusercontent.com/1507828/121949293-8556d600-cd15-11eb-88fa-74bba6fbded5.png)

**Comment by atopal** [comment]
Ah, already deployed. Neat 💯

**Comment by jessicaschilling** [comment]
one might even say "nifty" 🤣
