### ISSUE TITLE
[CONTENT] Minting on different blockchains

### ISSUE THREAD

**Issue by jessicaschilling** [protocol/nft-website#98]
This issue is for drafting content for the following:
- Title: Minting on different blockchains
- Address: `/how-to/minting-on-different-blockchains/`

**Comment by jochasinga** [comment]
I can help with this if it hasn't been taken. I've built this [pet store](https://github.com/jochasinga/flowwow) app on Flow + NFT.storage.

**Comment by yusefnapora** [comment]
That would be amazing, thanks @jochasinga. Great job on that, btw. I was actually just saying yesterday how cool it would be if you wanted to write something up for NFT School and had a note to ask you about it 😄

**Comment by dchoi27** [comment]
Hey @jochasinga, we're breaking out blockchain-specific tutorials into their own section in #135. We'll make individual issues for these chains and I'll tag you in the Flow one. Thanks so much!!!
